model:
  name: "HookedTransformerModel" # or "MaskedHeadTransformerModel"
  vocab_size: 2
  n_ctx: 10
  n_positions: 10
  d_head: 8
  n_head: 4
  n_layer: 4
  n_embd: 32
  n_inner: 64
  activation_function: "relu"

train:
  process: rrxor
  batch_size: 64
  learning_rate: 1e-3
  num_epochs: 24000
  device: "cuda"
  wandb_project_name: "hidden-markov-model"
  wandb_run_name: "model-rrxor-lr-1e-3-batch-64"

scheduler:
  type: "none"  # Options: "cosine", "step", "exponential", "plateau", "warmup_cosine", "none"
  min_lr: 0.000001  # For cosine annealing
  warmup_epochs: 1000  # For warmup_cosine
  step_size: 5000  # For step scheduler
  gamma: 0.5  # For step/exponential schedulers
  patience: 1000  # For plateau scheduler
  factor: 0.5  # For plateau scheduler
  
